### ISSUE TITLE
finish return types

### ISSUE THREAD

**Issue by cooper** [cooper/ferret#30]
## Concept
Return types were added to the compiler. It looks like:
```
func F {
    return "blah": Str
}
```
or for named returns
```
func F {
    A -> "asdf": Str
    B -> 4: Num
}
```

## Purpose
The purpose of this is that type interfaces will soon be able to require methods to have a certain return type:
```
type Iterable {
    can .iterator -> Iterator
}
```
or for named returns
```
type Person {
    can .info -> (name: Str, age: Num, sex: Gender)
}
```

## TODO

- [x] Add support for this new return type syntax
- [x] Add Verifier code which checks for return type mismatches within the same function
- [x] Include the compiler-determined string return types in the compiled code
- [x] Show return types in function signatures
- [x] Add support for the return type requirement syntax in type interfaces
- [x] Use SOIs to determine what the bareword types evaluate to
- [x] Implement actual checking of return types in type interfaces

**Comment by cooper** [comment]
```
<mad> i think i might just revert the past week worth of stuff ive done
<mad> these features
<mad> these type checking features 
<mad> are not appropriate for this type of language
<mad> are not appropriate for 
<mad> well
<mad> these type checking features
<mad> ARE appropriate in languages whose compilers are smart enough to detect discrepancies at compile time
<mad> when i made the type{} construct it was really simple
<mad> .e type Gender { :male; :female }
<booby> Interface 'Gender' { $obj }
<mad> .e Gender(:male)
<booby> :male
<mad> .e Gender(:blah)
<booby> undefined
<mad> when i added a way to test if an object has methods or properties then i wanted to make it possible to require that the arguments for the method are of certain type
<mad> thats when it got too complicated
<mad> i think i might get rid of the arg type and return type checking in interfaces
<mad> but still make it possible to just say it has to have this method
<mad> yeah
<mad> this is dumb
<mad> ok so
<mad> im not gonna revert 
<mad> what i did
<mad> but
<mad> im not adding return types to std lib
<mad> or any new code
<mad> bc 
<mad> it might be useful for SOME things
<mad> but not usually
<mad> it might be useful for like
<mad> you have two classes that are similar 
<mad> but slightly different
<mad> but you can use them in the same place
<mad> sometime
<mad> s
<mad> but when you wrote the classes you willingly put the return types such that the class would fit the protocol
<mad> ya
<mad> thats the only time return types would be useful
<mad> so it would be dumb to make it customary to include them
<mad> like all the time
```
